-- Generated by nwg-displays on 2026-06-06 at 17:49:40. Do not edit manually.

hl.monitor({
    output = "eDP-1",
    disabled = true
})
hl.monitor({
    output = "HDMI-A-1",
    mode = "1920x1080@120.0",
    position = "0x0",
    scale = 1.0
})
